### ISSUE TITLE
Breadcrumb doesnt'work with custom taxonomy

### ISSUE THREAD

**Issue by simoneprodesign** [ItalyStrap/advanced-control-manager#1]
Any solution with this?

Thanks

**Comment by overclokk** [comment]
Hi, I test it and I let you know soon

**Comment by simoneprodesign** [comment]
Thank you so much for ur fast reply, I'll waiting for us.

**Comment by overclokk** [comment]
@protasisimone I have fixed it and I'll update plugin soon in WordPress repo

**Comment by overclokk** [comment]
@protasisimone It's on the repo, let me know if it's all ok

**Comment by simoneprodesign** [comment]
It's all ok now, great!

Complimenti per la tempestiva risposta e risoluzione della problematica!
Grazie.

**Comment by overclokk** [comment]
Perfetto, grazie mille :-)
