### ISSUE TITLE
Error: Breadcrumbs.php on line 91

### ISSUE THREAD

**Issue by AndreaGelmini** [ItalyStrap/advanced-control-manager#15]
Ciao dopo l'ultimo aggiornamento mi viene fuori questo errore: 

Notice: Use of undefined constant GET_BLOGINFO_NAME - assumed 'GET_BLOGINFO_NAME' in /plugins/italystrap/core/Breadcrumbs.php on line 91

ho risolto cambiando cosi il codice.. 

`if ( ! isset( $bloginfo_name ) ) { $bloginfo_name = esc_attr( get_bloginfo('name') ); }`

Giusto per far girare il sito di test.

**Comment by overclokk** [comment]
La costante era definita solo nel tema, ora lo è.
Grazie della segnalazione.
