### ISSUE TITLE
Non riesco ad attivare la altre sezioni.

### ISSUE THREAD

**Issue by Sam9999it** [ItalyStrap/advanced-control-manager#16]
![screenshot from 2017-09-24 07-16-05](https://user-images.githubusercontent.com/32234346/30779731-e6adca6e-a0f8-11e7-895e-bbccb69c0cdd.png)
Ho solo la sidebar e 4 foother che sono nel tema ItalyStrap, anche nei setting non trovo come fare per avere più sezioni distinte per i wdget. Sto rpvando il tema con il plugin sul sito www.lavoro.tk. Te l'ho anche chiesto in riunione al WCAP ed hai detto che le sezioni vi sono, ma non le trovo. :)

**Comment by overclokk** [comment]
Aggiungi la costante `ITALYSTRAP_BETA` al file wp_config.php poi nelle impostazioni di ACM puoi selezionare la Widget Areas.

```php
define( 'ITALYSTRAP_BETA', true );
```

Dovrebbe essere scritto anche nel readme :-) https://github.com/ItalyStrap/advanced-control-manager/blob/master/README.md

**Comment by Sam9999it** [comment]
Ciao, si ora ci riesco, il codicino però va messo in alto in wp-config.php
Ho adesso un problema con il boilerhtml5. magari tra un po' ricontrollo come si chiama, sono essenziali tutte le cose che scrive in .htaccess? Il mio serverino è delicato e mi da subito errore 500 sulla pagina, apena metto cose in .htaccess anche perché mi pare che non vuole comandi duplicati con quanto già scritto nel file di configurazione di php 7.0 e apache2 o altro del genere, quindi mi dovrei stare a ricontrollare tutti i mod che vengono richiamati per sapere quelli compatibili con il mio sistema e quelli non compatibili, o come e dove richiamarli..

**Comment by overclokk** [comment]
Le cose che vengono aggiunte nel file htaccess molte sono commentate quindi non eseguite, puoi verificare quali ti servono e quali no, quello che non usi lo puoi eliminare senza problemi.

**Comment by Sam9999it** [comment]
Al momento, visto che per ragioni di sicurezza dettate da loginizer, il file .htaccess non è scrivibile e quindi non vengono apportate modifiche. Il sito web di prova appare funzionare.
Mi potresti indicare i mod necessari o indispensabili in maniera da provare ad abilitarne uno per volta?

**Comment by overclokk** [comment]
Quello che ti consiglio è di studiarne uno alla volta e vedere il risultato, sono commentati quindi bene o male sai già cosa fanno, altrimenti molto meglio il supporto di google per avere più informazioni su quel file.

Comunque se non li vuoi usare li puoi cancellare senza problema.

Nelle prossime versioni la metto come opzione.

**Comment by Sam9999it** [comment]
E' quello che farò appena ho della voglia e del tempo.. commentarli tutti, i mod, e decommentarne uno alla volta per vede quelli che funzionano e magari a quelli che non funzionano capire il perché e se vi sono alternative oppure no..
