### ISSUE TITLE
Potenziale problema tra LazyLoad e CPT

### ISSUE THREAD

**Issue by AndreaGelmini** [ItalyStrap/advanced-control-manager#4]
Ciao. 

Ho notato questi due potenzieli "problemi" che si presentano quando ho LazyLoad attivato e provo a pubblicare un CPT

Problema numero uno, la conversione in base64 mi fà conparire una immagine totalmente grigia. 
Problema numero due, il meta schema.org creato per l'immagine viene riconosciuto come sbagliato dal google schema test tool. 

Sperando di essere stato utile.

**Comment by overclokk** [comment]
Ciao @AndrGelmini 
l'immagine grigia è quella che viene caricata come temporanea al posto dell'innagine finale, poi appena il download della pagina è terminato viene sostituita dall'originale.

Per chema.org faccio un controllo.

Grazie mille.

**Comment by AndreaGelmini** [comment]
Ciao @overclokk 

Devo ammettere che lo avevo pensato al che ho fatto delle prove.  

Il a tempo di caricamento della pagina ho aspettato circa 5 minuti e l'immagine grigia non spariva ho provato a ricaricare e mi dava ancora grigia...  questa prova l'ho fatta con immagine caricata come media e con immagine caricata via url esterno... . 

Riprovo a fare i test

Per schema.org il problema meta img me lo dà come una uno schema non riconosciuto o senza impostazione.

**Comment by overclokk** [comment]
Ciao @AndrGelmini con la nuova versione riscontri ancora questo problema?

**Comment by AndreaGelmini** [comment]
No no. Con la nuova versione sembra funzionare.

**Comment by overclokk** [comment]
Perfetto, allora chiudo
