### ISSUE TITLE
Beta tester for ItalyStrap plugin 2.0.x-xx.x

### ISSUE THREAD

**Issue by overclokk** [ItalyStrap/advanced-control-manager#5]
Post here your feedback for v.2.0.x-beta

**Comment by overclokk** [comment]
v.2.0.0-rc.1 http://goo.gl/WBauUb

**Comment by AndreaGelmini** [comment]
Sto testando il plugin su server altervista con ultima versione di wp con italystrap come tema quando lo vado ad installare mi restituisce un php errore per la una [ alla riga 116 del file init.php riporto la riga 116 di detto file

`<?php
    $injector->define( 'ItalyStrap\Widget\Widget_Attributes', ['fields_type' => 'ItalyStrap\Admin\Fields'] );
?>`

**Comment by overclokk** [comment]
Ciao @AndrGelmini 
Mi potresti dire versione php e l'esatto errore php?

**Comment by AndreaGelmini** [comment]
Ciao e scusa il ritardo ...  

Versione di PHP 5.6 il sito di prova è hostato su Altervista Tema Child Italystrap 

Errore 

`Parse error: syntax error, unexpected '[' in /membri/agconsulting/test-nl-aef/wp-content/plugins/italystrap/init.php on line 116`

**Comment by AndreaGelmini** [comment]
Sto testando lo stesso sito.. ( uno è la fotocopia dell'altro) 

nel secondo che è hostato su 1hi.it l'errore precedente non è presente ma ho difficoltà a far visualizzare la/il breadcrumbs.. 

1 - il messaggio di deprecazione delle funzione riporta questa dicitura.. (ItalyStrap\Core\breadcrumbs) come suggerimento per la nuova classe. 

2 - apportate la adeguate modifiche mi vengono portanti un paio di errori.
`Notice: Use of undefined constant HOME_URL - assumed 'HOME_URL' in /home/aspxzbip/public_html/testaef/wp-content/plugins/italystrap/core/breadcrumbs/class-breadcrumbs.php on line 147`

**Comment by overclokk** [comment]
Ciao,
per quanto riguarda il primo errore è strano perché la scrittura degli array corta c'è dalla 5.4 e tu hai la 5.6

Per il secondo problema invece:
1) Si, il vecchio breadcrumbs è stato deprecato, nel readme ho scritto come usare quello nuovo
2) Ok, HOME_URL era definita solo nel tema e non nel plugin, ora la aggiungo anche al plugin.

Intanto grazie mille

**Comment by AndreaGelmini** [comment]
Per il primo errore potrebbe essere un errore dell'hosting "altervista"

Intanto continuo a testare e riporterò i vari errori che ricontrerò man mano che testo.

**Comment by overclokk** [comment]
Ottimo, perfetto.
Ne prossimi giorni sarà disponibile la rc2
